### PR TITLE
Added Dirtside 2 game and unit card.

### PR DESCRIPTION
**Pull request by mattcaron**

### CODE REVIEW

**Comment by Gulix** [comment]
I'll look into it this weekend to merge it !

**Comment by mattcaron** [comment]
Not to be a bother, but have you had a chance to look at this PR?

**Comment by Gulix** [comment]
Frankly : no, not had the time to get back to this project.
I will at the end of the week, I put a remainder to not forget it.

**Comment by mattcaron** [comment]
I have twin 3 year old boys. :-) Trust me, I know how time can get away from you.

**Comment by Gulix** [comment]
I've decided to not include those templates in the project.
They're good and functional, but they don't fit this project 
"My Templates for Magic Set Editor" => they're not my templates, and I don't have the need for these templates, not the time or ability to maintain them. 

I will gladly accept Pull Request about modifications in my own templates, but not outside templates, that are, in my mind, out of scope with this project.

Thanks

**Pull request closed without merging**
